### ISSUE TITLE
[win 10] Building wheel for tensorflow-gnn (setup.py) ... error 

### ISSUE THREAD

**Issue by 943fansi** [tensorflow/gnn#10]
Building wheel for tensorflow-gnn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\dell\Miniconda3\envs\tfgnn\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-req-build-dipdqlp_\\setup.py'"'"'; __file__='"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-req-build-dipdqlp_\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\dell\AppData\Local\Temp\pip-wheel-64ktaxfy'
       cwd: C:\Users\dell\AppData\Local\Temp\pip-req-build-dipdqlp_\
  Complete output (52 lines):
  running bdist_wheel
  running build
  running bazel_build
  Starting local Bazel server and connecting to it...
  Loading:
  Loading: 0 packages loaded
  Loading: 0 packages loaded
  Loading: 0 packages loaded
  Loading: 0 packages loaded
  Loading: 0 packages loaded
  Loading: 0 packages loaded
  Loading: 0 packages loaded
  DEBUG: C:/users/dell/_bazel_dell/hwkq7w65/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
  Loading: 0 packages loaded
  Loading: 0 packages loaded
  Analyzing: target //package:move_generated_files (1 packages loaded, 0 targets configured)
  ERROR: C:/users/dell/appdata/local/temp/pip-req-build-dipdqlp_/package/BUILD:10:10: no such target '//tensorflow_gnn/sampler:sampling_spec_pb2.py': target 'sampling_spec_pb2.py' not declared in package 'tensorflow_gnn/sampler' defined by C:/users/dell/appdata/local/temp/pip-req-build-dipdqlp_/tensorflow_gnn/sampler/BUILD and referenced by '//package:move_generated_files'
  ERROR: Analysis of target '//package:move_generated_files' failed; build aborted: Analysis failed
  INFO: Elapsed time: 133.684s
  INFO: 0 processes.
  FAILED: Build did NOT complete successfully (10 packages loaded, 10 targets configured)
  ERROR: Build failed. Not running target
  FAILED: Build did NOT complete successfully (10 packages loaded, 10 targets configured)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\dell\AppData\Local\Temp\pip-req-build-dipdqlp_\setup.py", line 152, in <module>
      setup(
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\dell\AppData\Local\Temp\pip-req-build-dipdqlp_\setup.py", line 86, in run
      subprocess.check_call(
    File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['D:\\bazel\\bazel.exe', 'run', '-c', 'opt', '--experimental_repo_remote_exec', '--copt=-DWIN32_LEAN_AND_MEAN', '//package:move_generated_files']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for tensorflow-gnn
  Running setup.py clean for tensorflow-gnn
Failed to build tensorflow-gnn
Installing collected packages: tensorflow-gnn
    Running setup.py install for tensorflow-gnn ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\dell\Miniconda3\envs\tfgnn\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-req-build-dipdqlp_\\setup.py'"'"'; __file__='"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-req-build-dipdqlp_\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\dell\AppData\Local\Temp\pip-record-bmf2pzwg\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\dell\Miniconda3\envs\tfgnn\Include\tensorflow-gnn'
         cwd: C:\Users\dell\AppData\Local\Temp\pip-req-build-dipdqlp_\
    Complete output (45 lines):
    running install
    running build
    running bazel_build
    Loading:
    Loading: 0 packages loaded
    DEBUG: C:/users/dell/_bazel_dell/hwkq7w65/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
    Analyzing: target //package:move_generated_files (0 packages loaded, 0 targets configured)
    ERROR: C:/users/dell/appdata/local/temp/pip-req-build-dipdqlp_/package/BUILD:10:10: no such target '//tensorflow_gnn/sampler:sampling_spec_pb2.py': target 'sampling_spec_pb2.py' not declared in package 'tensorflow_gnn/sampler' defined by C:/users/dell/appdata/local/temp/pip-req-build-dipdqlp_/tensorflow_gnn/sampler/BUILD and referenced by '//package:move_generated_files'
    ERROR: Analysis of target '//package:move_generated_files' failed; build aborted: Analysis failed
    INFO: Elapsed time: 0.419s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    ERROR: Build failed. Not running target
    FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dell\AppData\Local\Temp\pip-req-build-dipdqlp_\setup.py", line 152, in <module>
        setup(
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\dell\AppData\Local\Temp\pip-req-build-dipdqlp_\setup.py", line 86, in run
        subprocess.check_call(
      File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['D:\\bazel\\bazel.exe', 'run', '-c', 'opt', '--experimental_repo_remote_exec', '--copt=-DWIN32_LEAN_AND_MEAN', '//package:move_generated_files']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\dell\Miniconda3\envs\tfgnn\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-req-build-dipdqlp_\\setup.py'"'"'; __file__='"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-req-build-dipdqlp_\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\dell\AppData\Local\Temp\pip-record-bmf2pzwg\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\dell\Miniconda3\envs\tfgnn\Include\tensorflow-gnn' Check the logs for full command output.
Traceback (most recent call last):
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\__main__.py", line 31, in <module>
    sys.exit(_main())
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_internal\cli\main.py", line 70, in main
    return command.main(cmd_args)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_internal\cli\base_command.py", line 98, in main
    return self._main(args)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_internal\cli\command_context.py", line 20, in main_context
    yield
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\contextlib.py", line 532, in __exit__
    raise exc_details[1]
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_internal\utils\temp_dir.py", line 75, in tempdir_registry
    yield _tempdir_registry
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\contextlib.py", line 517, in __exit__
    if cb(*exc_details):
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_internal\utils\temp_dir.py", line 37, in global_tempdir_manager
    _tempdir_manager = old_tempdir_manager
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\contextlib.py", line 532, in __exit__
    raise exc_details[1]
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\contextlib.py", line 517, in __exit__
    if cb(*exc_details):
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_internal\utils\temp_dir.py", line 165, in __exit__
    self.cleanup()
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_internal\utils\temp_dir.py", line 184, in cleanup
    rmtree(self._path)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\site-packages\pip\_internal\utils\misc.py", line 135, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\shutil.py", line 748, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\shutil.py", line 630, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\dell\Miniconda3\envs\tfgnn\lib\shutil.py", line 628, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-req-build-dipdqlp_'

**Comment by medwar99** [comment]
I have the same issue, but I think it's related to the install issue referenced in #7
