### ISSUE TITLE
Input to reshape is a tensor with 1800 values, but the requested shape has 2400 [Op:Reshape]

### ISSUE THREAD

**Issue by ly3106** [tensorflow/gnn#163]
When I run the `keras_minibatch_trainer.py` in the anaconda environment by the below instruction, occasionally it gets this error -  `Input to reshape is a tensor with 1800 values, but the requested shape has 2400 [Op:Reshape]`. According to the error info - 
`…int_arithmetic_sampler.py", line 530, in generate_subgraphs
    yield self.sample_sub_graph_tensor(`, I think that it has something to do with `int_arithmetic_sampler.py`. But I don't know why. Could you please help me to resolve the problem?
```
(tf2.x) bit202@bit202-OMEN:~$ python /home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/keras_minibatch_trainer.py
```
**Notice：**
I have changed 33rd line code of `keras_minibatch_trainer.py` from `from tensorflow_gnn.examples.in_memory import int_arithmetic_sampler`to`import int_arithmetic_sampler`. Because as a folder name`tensorflow_gnn` conflict with `tensorflow_gnn` lib.

Following is the log:
```bash
Epoch 7500/10000
1/1 [==============================] - ETA: 0s - loss: 1.0105 - acc: 0.71502022-10-25 10:49:59.399484: W tensorflow/core/framework/op_kernel.cc:1768] UNKNOWN: InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:GPU:0}} Input to reshape is a tensor with 1800 values, but the requested shape has 2400 [Op:Reshape]
Traceback (most recent call last):

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1107, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id.numpy()))

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 530, in generate_subgraphs
    yield self.sample_sub_graph_tensor(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 604, in sample_sub_graph_tensor
    walk_tree = self.random_walk_tree(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 574, in random_walk_tree
    process_sampling_spec_topologically(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 194, in process_sampling_spec_topologically
    process_callback(node)

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 566, in process_sampling_op
    next_nodes = self.sample_one_hop(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 499, in sample_one_hop
    next_nodes = tf.reshape(next_nodes, source_nodes.shape + [sample_size])

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:GPU:0}} Input to reshape is a tensor with 1800 values, but the requested shape has 2400 [Op:Reshape]


Traceback (most recent call last):
  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/keras_minibatch_trainer.py", line 136, in <module>
    app.run(main)
  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/keras_minibatch_trainer.py", line 118, in main
    keras_model.fit(
  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

2 root error(s) found.
  (0) UNKNOWN:  InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:GPU:0}} Input to reshape is a tensor with 1800 values, but the requested shape has 2400 [Op:Reshape]
Traceback (most recent call last):

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1107, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id.numpy()))

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 530, in generate_subgraphs
    yield self.sample_sub_graph_tensor(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 604, in sample_sub_graph_tensor
    walk_tree = self.random_walk_tree(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 574, in random_walk_tree
    process_sampling_spec_topologically(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 194, in process_sampling_spec_topologically
    process_callback(node)

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 566, in process_sampling_op
    next_nodes = self.sample_one_hop(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 499, in sample_one_hop
    next_nodes = tf.reshape(next_nodes, source_nodes.shape + [sample_size])

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:GPU:0}} Input to reshape is a tensor with 1800 values, but the requested shape has 2400 [Op:Reshape]


	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_14]]
  (1) UNKNOWN:  InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:GPU:0}} Input to reshape is a tensor with 1800 values, but the requested shape has 2400 [Op:Reshape]
Traceback (most recent call last):

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1107, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id.numpy()))

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 530, in generate_subgraphs
    yield self.sample_sub_graph_tensor(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 604, in sample_sub_graph_tensor
    walk_tree = self.random_walk_tree(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 574, in random_walk_tree
    process_sampling_spec_topologically(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 194, in process_sampling_spec_topologically
    process_callback(node)

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 566, in process_sampling_op
    next_nodes = self.sample_one_hop(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 499, in sample_one_hop
    next_nodes = tf.reshape(next_nodes, source_nodes.shape + [sample_size])

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:GPU:0}} Input to reshape is a tensor with 1800 values, but the requested shape has 2400 [Op:Reshape]


	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_test_function_109382]
2022-10-25 10:49:59.402005: W tensorflow/core/framework/op_kernel.cc:1768] UNKNOWN: InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:GPU:0}} Input to reshape is a tensor with 2400 values, but the requested shape has 1800 [Op:Reshape]
Traceback (most recent call last):

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1107, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id.numpy()))

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 530, in generate_subgraphs
    yield self.sample_sub_graph_tensor(

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 606, in sample_sub_graph_tensor
    return walk_tree.to_graph_tensor(self.gather_node_features_dict)

  File "/home/bit202/Programs/tensorflow_gnn/examples/in_memory_test2nd/int_arithmetic_sampler.py", line 319, in to_graph_tensor
    renumbered_dst = tf.searchsorted(unique_node_ids[dst_set_name], edges[1])

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/home/bit202/Programs/anaconda3/envs/tf2.x/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:GPU:0}} Input to reshape is a tensor with 2400 values, but the requested shape has 1800 [Op:Reshape]
```

**Comment by samihaija** [comment]
As I am getting to this issue very late, today's version looks different than the one on Oct 25. Can you let us know if you still get the same error if you re-run today (after syncing to the new repo?, or after pip install --pre ?)

**Comment by arnoegw** [comment]
Hi @ly3106 , can you still reproduce the problem? If not, I think we should close this issue.

**Comment by ly3106** [comment]
I haven't tested it against the latest version of TF-GNN. But I'll try it as soon as possible, please wait a few days.

**Comment by ly3106** [comment]
I re-run the program recently on both CPU and GPU. It works well on both computer units. So, you'll be able to close this issue, now. Think you very much. 

And following are my environment configurations. The GPU is an RTX2070, and some other essential versions are `python 3.10`, `tensorflow 2.11`, `tensorflow_gnn 0.5.0`, `cudatoolkit 11.2`, `cudnn 8.1`,`ogb 1.3.5`, and `torch 1.11.0`. All environment configurations of Anaconda are shown in the table.

Name |                   Version |                  Build  |Channel
|:-------- |:----- | -----:|:---
_libgcc_mutex             |0.1                        |main    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
_openmp_mutex             |5.1                       |1_gnu    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
absl-py                   |1.4.0                    |pypi_0    |pypi
apache-beam               |2.46.0                   |pypi_0    |pypi
astunparse                |1.6.3                    |pypi_0    |pypi
attrs                     |21.4.0                   |pypi_0    |pypi
bzip2                     |1.0.8                |h7b6447c_0    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
ca-certificates           |2023.01.10           |h06a4308_0    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
cachetools                |5.3.0                    |pypi_0    |pypi
certifi                   |2022.12.7                |pypi_0    |pypi
charset-normalizer        |3.1.0                    |pypi_0    |pypi
cloudpickle               |2.2.1                    |pypi_0    |pypi
cmake                     |3.26.1                   |pypi_0    |pypi
contextlib2               |21.6.0                   |pypi_0    |pypi
crcmod                    |1.7                      |pypi_0    |pypi
cudatoolkit               |11.2.2              |hbe64b41_10    |https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/conda-forge
cudnn                     |8.1.0.77             |h90431f1_0    |https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/conda-forge
dill                      |0.3.1.1                  |pypi_0    |pypi
docopt                    |0.6.2                    |pypi_0    |pypi
fastavro                  |1.7.3                    |pypi_0    |pypi
fasteners                 |0.18                     |pypi_0    |pypi
filelock                  |3.10.3                   |pypi_0    |pypi
flatbuffers               |23.3.3                   |pypi_0    |pypi
gast                      |0.4.0                    |pypi_0    |pypi
google-auth               |2.16.3                   |pypi_0    |pypi
google-auth-oauthlib      |0.4.6                    |pypi_0    |pypi
google-pasta              |0.2.0                    |pypi_0    |pypi
google-vizier             |0.1.4                    |pypi_0    |pypi
googleapis-common-protos  |1.59.0                   |pypi_0    |pypi
greenlet                  |2.0.2                    |pypi_0    |pypi
grpcio                    |1.48.2                   |pypi_0    |pypi
grpcio-tools              |1.48.2                   |pypi_0    |pypi
h5py                      |3.8.0                    |pypi_0    |pypi
hdfs                      |2.7.0                    |pypi_0    |pypi
httplib2                  |0.21.0                   |pypi_0    |pypi
idna                      |3.4                      |pypi_0    |pypi
jinja2                    |3.1.2                    |pypi_0    |pypi
joblib                    |1.2.0                    |pypi_0    |pypi
keras                    | 2.11.0                   |pypi_0    |pypi
ld_impl_linux-64          |2.38                 |h1181459_1    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libclang                  |16.0.0                   |pypi_0    |pypi
libffi                    |3.4.2                |h6a678d5_6    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libgcc-ng                 |11.2.0               |h1234567_1    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libgomp                   |11.2.0               |h1234567_1    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libstdcxx-ng              |11.2.0               |h1234567_1    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libuuid                   |1.41.5               |h5eee18b_0    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
lit                       |16.0.0                   |pypi_0    |pypi
littleutils               |0.2.2                    |pypi_0    |pypi
markdown                  |3.4.3                    |pypi_0    |pypi
markupsafe                |2.1.2                    |pypi_0    |pypi
ml-collections            |0.1.1                    |pypi_0    |pypi
mpmath                    |1.3.0                    |pypi_0    |pypi
ncurses                   |6.4                  |h6a678d5_0    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
networkx                  |3.0                      |pypi_0    |pypi
numpy                     |1.24.2                   |pypi_0    |pypi
nvidia-cublas-cu11        |11.10.3.66               |pypi_0    |pypi
nvidia-cuda-cupti-cu11    |11.7.101                 |pypi_0    |pypi
nvidia-cuda-nvrtc-cu11    |11.7.99                  |pypi_0    |pypi
nvidia-cuda-runtime-cu11  |11.7.99                  |pypi_0    |pypi
nvidia-cudnn-cu11         |8.5.0.96                 |pypi_0    |pypi
nvidia-cufft-cu11         |10.9.0.58                |pypi_0    |pypi
nvidia-curand-cu11        |10.2.10.91               |pypi_0    |pypi
nvidia-cusolver-cu11      |11.4.0.1                 |pypi_0    |pypi
nvidia-cusparse-cu11      |11.7.4.91                |pypi_0    |pypi
nvidia-nccl-cu11          |2.14.3                   |pypi_0    |pypi
nvidia-nvtx-cu11          |11.7.91                  |pypi_0    |pypi
oauthlib                  |3.2.2                    |pypi_0    |pypi
objsize                   |0.6.1                    |pypi_0    |pypi
ogb                       |1.3.5                    |pypi_0    |pypi
openssl                   |1.1.1t               |h7f8727e_0    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
opt-einsum                |3.3.0                    |pypi_0    |pypi
orjson                    |3.8.8                    |pypi_0    |pypi
outdated                  |0.2.2                    |pypi_0    |pypi
packaging                 |23.0                     |pypi_0    |pypi
pandas                    |1.5.3                    |pypi_0    |pypi
pip                       |23.0.1                   |pypi_0    |pypi
portpicker                |1.5.2                    |pypi_0    |pypi
proto-plus                |1.22.2                   |pypi_0    |pypi
protobuf                  |3.19.6                   |pypi_0    |pypi
psutil                    |5.9.4                    |pypi_0    |pypi
pyarrow                   |9.0.0                    |pypi_0    |pypi
pyasn1                    |0.4.8                    |pypi_0    |pypi
pyasn1-modules            |0.2.8                    |pypi_0    |pypi
pydot                     |1.4.2                    |pypi_0    |pypi
pymongo                   |3.13.0                   |pypi_0    |pypi
pyparsing                 |3.0.9                    |pypi_0    |pypi
python                    |3.10.10              |h7a1cb2a_2    |https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/main
python-dateutil           |2.8.2                    |pypi_0    |pypi
pytz                      |2022.7.1                 |pypi_0    |pypi
pyyaml                    |6.0                      |pypi_0    |pypi
readline                  |8.2                  |h5eee18b_0    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
regex                     |2023.3.23                |pypi_0    |pypi
requests                  |2.28.2                   |pypi_0    |pypi
requests-oauthlib         |1.3.1                    |pypi_0    |pypi
rsa                       |4.9                      |pypi_0    |pypi
scikit-learn              |1.2.2                    |pypi_0    |pypi
scipy                     |1.10.1                   |pypi_0    |pypi
setuptools                |65.6.3                   |pypi_0    |pypi
six                       |1.16.0                   |pypi_0    |pypi
sqlalchemy                |1.4.0                    |pypi_0    |pypi
sqlite                    |3.41.1               |h5eee18b_0    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
sympy                     |1.11.1                   |pypi_0    |pypi
tensorboard               |2.11.2                   |pypi_0    |pypi
tensorboard-data-server   |0.6.1                    |pypi_0    |pypi
tensorboard-plugin-wit    |1.8.1                    |pypi_0    |pypi
tensorflow                |2.11.0                   |pypi_0    |pypi
tensorflow-estimator      |2.11.0                   |pypi_0    |pypi
tensorflow-gnn            |0.5.0                    |pypi_0    |pypi
tensorflow-io-gcs-filesystem |0.31.0                   |pypi_0    |pypi
termcolor                 |2.2.0                    |pypi_0    |pypi
threadpoolctl             |3.1.0                    |pypi_0    |pypi
tk                        |8.6.12               |h1ccaba5_0    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
torch                     |1.11.0                   |pypi_0    |pypi
tqdm                      |4.65.0                   |pypi_0    |pypi
triton                    |2.0.0                    |pypi_0    |pypi
typing-extensions         |4.5.0                    |pypi_0    |pypi
tzdata                    |2022g                |h04d1e81_0    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
urllib3                   |1.26.15                  |pypi_0    |pypi
werkzeug                  |2.2.3                    |pypi_0    |pypi
wheel                     |0.38.4                   |pypi_0    |pypi
wrapt                     |1.15.0                   |pypi_0    |pypi
xz                        |5.2.10               |h5eee18b_1    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
zlib                      |1.2.13               |h5eee18b_0    |https://mirrors.ustc.edu.cn/anaconda/pkgs/main
zstandard                 |0.20.0                   |pypi_0    |pypi

**Comment by arnoegw** [comment]
Hi @ly3106 , thank you for confirming, and thank you for reporting the detailed versions. As you said, I'm going to close this now.
