### ISSUE TITLE
ValueError: Tensor conversion requested dtype variant

### ISSUE THREAD

**Issue by SidneyLann** [tensorflow/gnn#32]
W tensorflow/core/framework/op_kernel.cc:1733] INVALID_ARGUMENT: ValueError: Tensor conversion requested dtype variant for Tensor with dtype int64: <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>
Traceback (most recent call last):

  File "/home/sidney/.javacpp/cache/cpython-3.10.2-1.5.7-linux-x86_64.jar/org/bytedeco/cpython/linux-x86_64/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    return func(device, token, args)

  File "/home/sidney/.javacpp/cache/cpython-3.10.2-1.5.7-linux-x86_64.jar/org/bytedeco/cpython/linux-x86_64/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 148, in __call__
    outputs = self._call(device, args)

  File "/home/sidney/.javacpp/cache/cpython-3.10.2-1.5.7-linux-x86_64.jar/org/bytedeco/cpython/linux-x86_64/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 164, in _call
    outputs = [

  File "/home/sidney/.javacpp/cache/cpython-3.10.2-1.5.7-linux-x86_64.jar/org/bytedeco/cpython/linux-x86_64/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 165, in <listcomp>
    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),

  File "/home/sidney/.javacpp/cache/cpython-3.10.2-1.5.7-linux-x86_64.jar/org/bytedeco/cpython/linux-x86_64/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 132, in _convert
    return ops.convert_to_tensor(value, dtype=dtype)

  File "/home/sidney/.javacpp/cache/cpython-3.10.2-1.5.7-linux-x86_64.jar/org/bytedeco/cpython/linux-x86_64/lib/python3.10/site-packages/tensorflow/python/profiler/trace.py", line 183, in wrapped
    return func(*args, **kwargs)

  File "/home/sidney/.javacpp/cache/cpython-3.10.2-1.5.7-linux-x86_64.jar/org/bytedeco/cpython/linux-x86_64/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1662, in convert_to_tensor
    raise ValueError(

ValueError: Tensor conversion requested dtype variant for Tensor with dtype int64: <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>

**Comment by SidneyLann** [comment]
Python 3.10 should be Ok to use tf-gnn? Why it pass dtype variant for Tensor with dtype int64?
