### ISSUE TITLE
Dockerfile is not consistent with readme guide.

### ISSUE THREAD

**Issue by mhsong21** [tensorflow/gnn#678]
Hi, I got a problem building tfgnn image with Dockerfile on linux.

The problematic step is on `RUN python3 -m pip install /app`
As it throws an error as this:
```
ModuleNotFoundError: No module named 'numpy'
```

I tried installing numpy with pip, but I found that **Dockerfile does not have tensorflow installation step** which is inconsistent with the readme installation guide.

I added `RUN pip3 install tensorflow` and the build was successful.

I can write a pr for it.

Thanks.

Full log
```
Building wheels for collected packages: tensorflow-gnn, ml-collections
  Building wheel for tensorflow-gnn (pyproject.toml): started
  Building wheel for tensorflow-gnn (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for tensorflow-gnn (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [147 lines of output]
      running bdist_wheel
      running build
      running bazel_build
      Extracting Bazel installation...
      Starting local Bazel server and connecting to it...
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/4ce3e4da2e21ae4dfcee9366415e55f408c884ec.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading:
      Loading: 0 packages loaded
      Analyzing: target //package:move_generated_files (1 packages loaded, 0 targets configured)
      INFO: Repository local_config_python instantiated at:
        /app/WORKSPACE:14:14: in <toplevel>
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/tensorflow/workspace2.bzl:928:19: in workspace
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/tensorflow/workspace2.bzl:98:21: in _tf_toolchains
      Repository rule python_configure defined at:
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/third_party/py/python_configure.bzl:298:35: in <toplevel>
      INFO: Repository local_execution_config_python instantiated at:
        /app/WORKSPACE:14:14: in <toplevel>
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/tensorflow/workspace2.bzl:928:19: in workspace
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/tensorflow/workspace2.bzl:88:27: in _tf_toolchains
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
      Repository rule local_python_configure defined at:
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
      ERROR: An error occurred during the fetch of repository 'local_config_python':
         Traceback (most recent call last):
          File "/root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/third_party/py/python_configure.bzl", line 271, column 40, in _python_autoconf_impl
                  _create_local_python_repository(repository_ctx)
          File "/root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/third_party/py/python_configure.bzl", line 216, column 39, in _create_local_python_repository
                  numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
          File "/root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/third_party/py/python_configure.bzl", line 190, column 19, in _get_numpy_include
                  return execute(
          File "/root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                  fail(
      Error in fail: Problem getting numpy include path.
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'numpy'
      Is numpy installed?
      ERROR: /app/WORKSPACE:14:14: fetching python_configure rule //external:local_config_python: Traceback (most recent call last):
          File "/root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/third_party/py/python_configure.bzl", line 271, column 40, in _python_autoconf_impl
                  _create_local_python_repository(repository_ctx)
          File "/root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/third_party/py/python_configure.bzl", line 216, column 39, in _create_local_python_repository
                  numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
          File "/root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/third_party/py/python_configure.bzl", line 190, column 19, in _get_numpy_include
                  return execute(
          File "/root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                  fail(
      Error in fail: Problem getting numpy include path.
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'numpy'
      Is numpy installed?
      Analyzing: target //package:move_generated_files (39 packages loaded, 21 targets configured)
      INFO: Repository rules_cc instantiated at:
        /app/WORKSPACE:16:14: in <toplevel>
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/tensorflow/workspace1.bzl:18:28: in workspace
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/rules_cuda/cuda/dependencies.bzl:72:18: in rules_cuda_dependencies
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/rules_cuda/cuda/dependencies.bzl:35:17: in _rules_cc
      Repository rule http_archive defined at:
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
      INFO: Repository go_sdk instantiated at:
        /app/WORKSPACE:18:14: in <toplevel>
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/org_tensorflow/tensorflow/workspace0.bzl:134:20: in workspace
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/io_bazel_rules_go/go/private/sdk.bzl:431:28: in go_register_toolchains
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/io_bazel_rules_go/go/private/sdk.bzl:130:21: in go_download_sdk
      Repository rule _go_download_sdk defined at:
        /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/io_bazel_rules_go/go/private/sdk.bzl:117:35: in <toplevel>
      ERROR: Analysis of target '//package:move_generated_files' failed; build aborted: Problem getting numpy include path.
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'numpy'
      Is numpy installed?
      INFO: Elapsed time: 38.579s
      INFO: 0 processes.
      FAILED: Build did NOT complete successfully (39 packages loaded, 21 targets configured)
      ERROR: Build failed. Not running target
      Traceback (most recent call last):
        File "/opt/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 145, in <module>
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 369, in run
          self.run_command("build")
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-3yj6npkj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 86, in run
        File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/bazel', 'run', '-c', 'opt', '--experimental_repo_remote_exec', '@tensorflow_gnn//package:move_generated_files']' returned non-zero exit status 1.
```

**Comment by mhsong21** [comment]
As Dockerfile changed after v1.0.0 [release](https://github.com/tensorflow/gnn/releases/tag/v1.0.0), I'm closing the issue.
